name: golang-pipeline

on: push

env:
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0
  REDIS_ADDRESS: ${{ secrets.REDIS_ADDRESS }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
  NEXT_PUBLIC_SOCKET_URL: ${{ secrets.NEXT_PUBLIC_SOCKET_URL }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      
      - name: Extract Version
        id: version_step
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          MAIN_REPO="${{ secrets.DOCKERHUB_USERNAME }}/go-party"
          APP_REPO="${{ secrets.DOCKERHUB_USERNAME }}/go-party-app"
          
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "MAIN_VERSION_TAG=$MAIN_REPO:$VERSION" >> $GITHUB_OUTPUT
          echo "MAIN_LATEST_TAG=$MAIN_REPO:latest" >> $GITHUB_OUTPUT
          echo "APP_VERSION_TAG=$APP_REPO:$VERSION" >> $GITHUB_OUTPUT
          echo "APP_LATEST_TAG=$APP_REPO:latest" >> $GITHUB_OUTPUT
      
      - name: Print Version
        run: |
          echo ${{steps.version_step.outputs.MAIN_VERSION_TAG}}
          echo ${{steps.version_step.outputs.MAIN_LATEST_TAG}}
          echo ${{steps.version_step.outputs.APP_VERSION_TAG}}
          echo ${{steps.version_step.outputs.APP_LATEST_TAG}}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push main image
        id: docker_build_main
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ steps.version_step.outputs.MAIN_VERSION_TAG }}
            ${{ steps.version_step.outputs.MAIN_LATEST_TAG }}
          build-args: |
            VERSION=${{ steps.version_step.outputs.VERSION }}
            REDIS_ADDRESS=${{ secrets.REDIS_ADDRESS }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}

      - name: Build and push app image
        id: docker_build_app
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: |
            ${{ steps.version_step.outputs.APP_VERSION_TAG }}
            ${{ steps.version_step.outputs.APP_LATEST_TAG }}
          build-args: |
            VERSION=${{ steps.version_step.outputs.VERSION }}
            NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
            NEXT_PUBLIC_SOCKET_URL=${{ secrets.NEXT_PUBLIC_SOCKET_URL }}
            